<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <AssemblyName>AvgSellPrice.Server</AssemblyName>
    <RootNamespace>AvgSellPrice.Server</RootNamespace>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SPTarkov.Common" Version="4.0.13" />
    <PackageReference Include="SPTarkov.DI" Version="4.0.13" />
    <PackageReference Include="SPTarkov.Server.Core" Version="4.0.13" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>..\..\..\..\..\SPT\BepInEx\core\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\..\..\..\..\SPT\EscapeFromTarkov_Data\Managed\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>..\..\..\..\..\SPT\BepInEx\core\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="Comfort">
      <HintPath>..\..\..\..\..\SPT\EscapeFromTarkov_Data\Managed\Comfort.dll</HintPath>
    </Reference>
    <Reference Include="Sirenix.Serialization">
      <HintPath>..\..\..\..\..\SPT\EscapeFromTarkov_Data\Managed\Sirenix.Serialization.dll</HintPath>
    </Reference>
    <Reference Include="spt-reflection">
      <HintPath>..\..\..\..\..\SPT\BepInEx\plugins\spt\spt-reflection.dll</HintPath>
    </Reference>
    <Reference Include="SPTarkov.Reflection">
      <HintPath>..\..\..\..\..\SPT\SPT\SPTarkov.Reflection.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>..\..\..\..\..\SPT\EscapeFromTarkov_Data\Managed\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\..\..\..\..\SPT\EscapeFromTarkov_Data\Managed\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\..\..\..\SPT\EscapeFromTarkov_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\..\..\..\..\SPT\EscapeFromTarkov_Data\Managed\UnityEngine.UI.dll</HintPath>
    </Reference>
  </ItemGroup>

  <Target Name="CopyToMods" AfterTargets="Build">
    <Copy SourceFiles="$(OutputPath)AvgSellPrice.Server.dll" DestinationFolder="$(MSBuildProjectDirectory)/output" />
    <Copy SourceFiles="$(OutputPath)AvgSellPrice.Server.dll" DestinationFolder="C:\SPT\SPT\user\mods\AvgSellPriceServer" Condition="'$(DeployToSpt)' == 'true'" />
    <Copy SourceFiles="$(OutputPath)AvgSellPrice.Server.pdb" DestinationFolder="C:\SPT\SPT\user\mods\AvgSellPriceServer" Condition="'$(DeployToSpt)' == 'true' And Exists('$(OutputPath)AvgSellPrice.Server.pdb')" />
  </Target>
</Project>
